let current=0;const savedAnswers=[];const start=document.getElementById('start'),quiz=document.getElementById('quiz'),result=document.getElementById('result'),startBtn=document.getElementById('startBtn'),nextBtn=document.getElementById('nextBtn'),restartBtn=document.getElementById('restartBtn'),counter=document.getElementById('counter'),progressFill=document.getElementById('progressFill'),questionTitle=document.getElementById('questionTitle'),answerArea=document.getElementById('answerArea');
function imgName(qi,oi){return `images/q${qi+1}-${['a','b','c','d'][oi]}.jpg`}
function fallbackImage(img){if(img.dataset.triedPng!=='1'&&img.src.endsWith('.jpg')){img.dataset.triedPng='1';img.src=img.src.replace('.jpg','.png');return}img.onerror=null;img.src='images/placeholder.svg'}
function renderTextOptions(q,revealText=null){const list=document.createElement('div');list.className='text-list';q.options.forEach(option=>{const btn=document.createElement('button');btn.type='button';btn.className='text-answer';btn.textContent=option;btn.onclick=()=>{document.querySelectorAll('.text-answer').forEach(e=>e.classList.remove('selected'));btn.classList.add('selected');savedAnswers[current]=option;nextBtn.disabled=false;if(revealText){const r=document.getElementById('reveal');r.textContent=revealText;r.style.display='block'}};list.appendChild(btn)});answerArea.appendChild(list)}
function renderQuestion(){const q=questions[current];nextBtn.disabled=true;nextBtn.textContent=current===questions.length-1?'Vedi risultato':'Prossima domanda';counter.textContent=`Domanda ${current+1} di ${questions.length}`;progressFill.style.width=`${(current/questions.length)*100}%`;questionTitle.textContent=q.title;answerArea.innerHTML='';
if(q.type==='section'){answerArea.innerHTML='<p class="subtitle" style="text-align:left;margin:0;">La procedura richiede massima sincerità, totale concentrazione e nessuna responsabilità da parte del test.</p>';nextBtn.disabled=false;return}
if(q.type==='imageChoice'){const grid=document.createElement('div');grid.className='answers-grid';q.options.forEach((option,index)=>{const card=document.createElement('article');card.className='card';card.innerHTML=`<img src="${imgName(current,index)}" alt="${option}" onerror="fallbackImage(this)"><div class="label">${option}</div>`;card.onclick=()=>{document.querySelectorAll('.card').forEach(e=>e.classList.remove('selected'));card.classList.add('selected');savedAnswers[current]=option;nextBtn.disabled=false};grid.appendChild(card)});answerArea.appendChild(grid)}
if(q.type==='textChoice')renderTextOptions(q);
if(q.type==='singleImageChoice'){answerArea.innerHTML=`<img class="single-img" src="${q.image}" alt="Immagine test" onerror="fallbackImage(this)">`;renderTextOptions(q)}
if(q.type==='eyes'){answerArea.innerHTML=`<img class="single-img" src="${q.image}" alt="Occhi" onerror="fallbackImage(this)">`;renderTextOptions(q,q.reveal);const d=document.createElement('div');d.id='reveal';d.className='reveal';answerArea.appendChild(d)}
if(q.type==='slider'){answerArea.innerHTML=`<div class="input-panel"><div>Valore selezionato:</div><div class="slider-value" id="sliderValue">5</div><input id="slider" type="range" min="1" max="10" value="5"><p class="small">${q.note||''}</p><textarea id="motivation" placeholder="Motiva la risposta."></textarea></div>`;document.getElementById('slider').oninput=e=>document.getElementById('sliderValue').textContent=e.target.value;nextBtn.disabled=false}
if(q.type==='open'){answerArea.innerHTML=`<div class="input-panel"><textarea id="openAnswer" placeholder="${q.placeholder||'Scrivi qui...'}"></textarea></div>`;nextBtn.disabled=false}
if(q.type==='timedOpen'){answerArea.innerHTML=`<div class="input-panel"><p class="small">${q.note}</p><div class="countdown" id="countdown">5</div><textarea id="timedAnswer" placeholder="${q.placeholder}"></textarea></div>`;nextBtn.disabled=false;let s=5;const c=document.getElementById('countdown');const t=setInterval(()=>{s--;c.textContent=s;if(s<=0)clearInterval(t)},1000)}}
startBtn.onclick=()=>{start.classList.add('hidden');quiz.classList.remove('hidden');renderQuestion()};
nextBtn.onclick=()=>{current++;if(current>=questions.length){quiz.classList.add('hidden');result.classList.remove('hidden')}else renderQuestion()};
restartBtn.onclick=()=>{current=0;result.classList.add('hidden');start.classList.remove('hidden')};
